Add missing notebooks
Previous push failed:
```
error: RPC failed; curl 55 OpenSSL SSL_write: Connection was aborted, errno 10053
fatal: the remote end hung up unexpectedly
fatal: the remote end hung up unexpectedly
```